theme: minima
# site.url: https://mickfuzz.github.io/phd4/
# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

header_pages:
 - about.md
 - index.md
 - thesis_chapters.md
 - book_chapters.md
 - blogs.md
 - other.md


title: PhD Writing - Game Making with Families
description: A git approach to writing a phd

url: https://mickfuzz.github.io
#url: https://localhost


baseurl: /phd
imgurl: https://github.com/mickfuzz/phd/blob/master/
show_excerpts: true


#theme: jekyll-theme-minimal

# publishing information
# pandoc -s -o 3M_framework.odt --lua-filter=../pandoctest/zotero.lua --filter=pandoc-citeproc  2021-03-20-3M-framework.md
